name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v > /usr/src/app/logs/test/test.txt
    - name: Send pull request number to endpoint
      if: github.event.pull_request.number != null
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        curl -X POST -H "Content-Type: application/json" -d "{\"pull_request_number\": \"$PR_NUMBER\"}" https://0fa7-23-112-11-217.ngrok-free.app/test