name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |        
        pytest -v > /usr/src/app/logs/test/test.txt
        TEST_OUTPUT=$(cat /usr/src/app/logs/test/test.txt)
        curl -X POST -H "Content-Type: application/json" -d "{\"test_results\": \"$TEST_OUTPUT\"}" https://cad8-23-112-11-217.ngrok-free.app/test